use jobboard;
insert into wants (WantID, ApplicantID, WantDescription) values (1, '27', 'nam congue risus semper porta volutpat quam');
insert into wants (WantID, ApplicantID, WantDescription) values (2, '4', 'eu pede');
insert into wants (WantID, ApplicantID, WantDescription) values (3, '32', 'lacinia');
insert into wants (WantID, ApplicantID, WantDescription) values (4, '15', 'nulla tellus in sagittis dui vel nisl');
insert into wants (WantID, ApplicantID, WantDescription) values (5, '9', 'in libero ut massa volutpat convallis morbi');
insert into wants (WantID, ApplicantID, WantDescription) values (6, '36', 'orci mauris lacinia sapien');
insert into wants (WantID, ApplicantID, WantDescription) values (7, '11', 'justo maecenas rhoncus aliquam lacus morbi quis tortor');
insert into wants (WantID, ApplicantID, WantDescription) values (8, '35', 'feugiat non pretium quis lectus suspendisse');
insert into wants (WantID, ApplicantID, WantDescription) values (9, '39', 'justo nec condimentum neque sapien');
insert into wants (WantID, ApplicantID, WantDescription) values (10, '43', 'pede morbi porttitor lorem id ligula');
insert into wants (WantID, ApplicantID, WantDescription) values (11, '37', 'et magnis dis parturient');
insert into wants (WantID, ApplicantID, WantDescription) values (12, '40', 'augue aliquam erat volutpat in congue etiam justo');
insert into wants (WantID, ApplicantID, WantDescription) values (13, '18', 'eleifend quam a odio in hac');
insert into wants (WantID, ApplicantID, WantDescription) values (14, '30', 'nunc purus phasellus in felis donec semper');
insert into wants (WantID, ApplicantID, WantDescription) values (15, '3', 'mi nulla');
insert into wants (WantID, ApplicantID, WantDescription) values (16, '23', 'orci luctus et ultrices posuere cubilia curae donec');
insert into wants (WantID, ApplicantID, WantDescription) values (17, '34', 'aliquet massa id lobortis convallis tortor risus dapibus');
insert into wants (WantID, ApplicantID, WantDescription) values (18, '10', 'nibh in lectus pellentesque at nulla suspendisse potenti');
insert into wants (WantID, ApplicantID, WantDescription) values (19, '22', 'a odio');
insert into wants (WantID, ApplicantID, WantDescription) values (20, '46', 'cursus urna ut tellus nulla ut erat');
insert into wants (WantID, ApplicantID, WantDescription) values (21, '38', 'lorem ipsum dolor sit');
insert into wants (WantID, ApplicantID, WantDescription) values (22, '31', 'porttitor lorem id ligula suspendisse');
insert into wants (WantID, ApplicantID, WantDescription) values (23, '8', 'tempor turpis nec euismod scelerisque quam');
insert into wants (WantID, ApplicantID, WantDescription) values (24, '26', 'faucibus accumsan odio curabitur convallis');
insert into wants (WantID, ApplicantID, WantDescription) values (25, '33', 'nec sem duis aliquam');
insert into wants (WantID, ApplicantID, WantDescription) values (26, '25', 'dolor vel est donec odio justo');
insert into wants (WantID, ApplicantID, WantDescription) values (27, '48', 'amet cursus id turpis integer');
insert into wants (WantID, ApplicantID, WantDescription) values (28, '28', 'nec molestie sed justo pellentesque viverra pede ac');
insert into wants (WantID, ApplicantID, WantDescription) values (29, '41', 'rutrum ac lobortis');
insert into wants (WantID, ApplicantID, WantDescription) values (30, '45', 'donec');
insert into wants (WantID, ApplicantID, WantDescription) values (31, '24', 'at nunc commodo placerat praesent');
insert into wants (WantID, ApplicantID, WantDescription) values (32, '42', 'fringilla rhoncus mauris enim');
insert into wants (WantID, ApplicantID, WantDescription) values (33, '50', 'vel dapibus at diam nam tristique tortor eu');
insert into wants (WantID, ApplicantID, WantDescription) values (34, '1', 'velit id pretium');
insert into wants (WantID, ApplicantID, WantDescription) values (35, '2', 'nunc donec quis');
insert into wants (WantID, ApplicantID, WantDescription) values (36, '12', 'vestibulum sagittis sapien cum sociis natoque');
insert into wants (WantID, ApplicantID, WantDescription) values (37, '13', 'at lorem integer tincidunt');
insert into wants (WantID, ApplicantID, WantDescription) values (38, '29', 'neque aenean auctor gravida sem praesent id');
insert into wants (WantID, ApplicantID, WantDescription) values (39, '21', 'elit sodales scelerisque mauris sit amet');
insert into wants (WantID, ApplicantID, WantDescription) values (40, '6', 'id pretium iaculis diam erat fermentum justo');
insert into wants (WantID, ApplicantID, WantDescription) values (41, '5', 'tempus vivamus in felis eu sapien');
insert into wants (WantID, ApplicantID, WantDescription) values (42, '16', 'vel augue');
insert into wants (WantID, ApplicantID, WantDescription) values (43, '19', 'interdum mauris ullamcorper purus');
insert into wants (WantID, ApplicantID, WantDescription) values (44, '17', 'leo pellentesque ultrices mattis odio donec vitae nisi');
insert into wants (WantID, ApplicantID, WantDescription) values (45, '47', 'vestibulum sit amet cursus id');
insert into wants (WantID, ApplicantID, WantDescription) values (46, '44', 'sodales sed tincidunt eu felis');
insert into wants (WantID, ApplicantID, WantDescription) values (47, '49', 'aliquet massa');
insert into wants (WantID, ApplicantID, WantDescription) values (48, '14', 'cras in purus eu');
insert into wants (WantID, ApplicantID, WantDescription) values (49, '7', 'turpis integer aliquet massa id');
insert into wants (WantID, ApplicantID, WantDescription) values (50, '20', 'lectus in est risus auctor sed');
