use jobboard;
insert into skill (skillID, Name) values (1, 'TVC');
insert into skill (skillID, Name) values (2, 'Drama');
insert into skill (skillID, Name) values (3, 'PTLLS');
insert into skill (skillID, Name) values (4, 'RTOS');
insert into skill (skillID, Name) values (5, 'Disability Insurance');
insert into skill (skillID, Name) values (6, 'VoIP');
insert into skill (skillID, Name) values (7, 'PCI Standards');
insert into skill (skillID, Name) values (8, 'Tutoring');
insert into skill (skillID, Name) values (9, 'Embedded Systems');
insert into skill (skillID, Name) values (10, 'HMO');
insert into skill (skillID, Name) values (11, 'BMP design');
insert into skill (skillID, Name) values (12, 'DP');
insert into skill (skillID, Name) values (13, 'Construction Management');
insert into skill (skillID, Name) values (14, 'IWR');
insert into skill (skillID, Name) values (15, 'Olfaction');
insert into skill (skillID, Name) values (16, 'DNA methylation');
insert into skill (skillID, Name) values (17, 'PCR');
insert into skill (skillID, Name) values (18, 'Aquisition');
insert into skill (skillID, Name) values (19, 'PDMLink');
insert into skill (skillID, Name) values (20, 'ODE');
insert into skill (skillID, Name) values (21, 'Vendor Management');
insert into skill (skillID, Name) values (22, 'Mortgage Underwriting');
insert into skill (skillID, Name) values (23, 'Supply Management');
insert into skill (skillID, Name) values (24, 'Long-term Care');
insert into skill (skillID, Name) values (25, 'DDR2');
insert into skill (skillID, Name) values (26, 'vBulletin');
insert into skill (skillID, Name) values (27, 'Xajax');
insert into skill (skillID, Name) values (28, 'Brochures');
insert into skill (skillID, Name) values (29, 'QAS');
insert into skill (skillID, Name) values (30, 'Mental Health Counseling');
insert into skill (skillID, Name) values (31, 'Workplace Violence');
insert into skill (skillID, Name) values (32, 'CMMI Level 5');
insert into skill (skillID, Name) values (33, 'Xytech');
insert into skill (skillID, Name) values (34, 'Natural Gas');
insert into skill (skillID, Name) values (35, 'Civil Rights');
insert into skill (skillID, Name) values (36, 'KNX');
insert into skill (skillID, Name) values (37, 'TMDLs');
insert into skill (skillID, Name) values (38, 'VSEO');
insert into skill (skillID, Name) values (39, 'Zend Certified Engineer');
insert into skill (skillID, Name) values (40, 'LDOM');
insert into skill (skillID, Name) values (41, 'Organization Skills');
insert into skill (skillID, Name) values (42, 'Urban');
insert into skill (skillID, Name) values (43, 'Contractual Agreements');
insert into skill (skillID, Name) values (44, 'cXML');
insert into skill (skillID, Name) values (45, 'EWP');
insert into skill (skillID, Name) values (46, 'eHealth');
insert into skill (skillID, Name) values (47, 'NGP');
insert into skill (skillID, Name) values (48, 'LCD');
insert into skill (skillID, Name) values (49, 'HR Transformation');
insert into skill (skillID, Name) values (50, 'DDS');
