insert into skill_test (SkillTestID, SKillID, Name) values (1, '31', 'integer ac leo');
insert into skill_test (SkillTestID, SKillID, Name) values (2, '28', 'non velit nec nisi');
insert into skill_test (SkillTestID, SKillID, Name) values (3, '30', 'aliquet maecenas leo');
insert into skill_test (SkillTestID, SKillID, Name) values (4, '13', 'id pretium iaculis diam erat');
insert into skill_test (SkillTestID, SKillID, Name) values (5, '35', 'suspendisse potenti cras in');
insert into skill_test (SkillTestID, SKillID, Name) values (6, '47', 'cubilia curae duis faucibus accumsan');
insert into skill_test (SkillTestID, SKillID, Name) values (7, '24', 'ut ultrices vel');
insert into skill_test (SkillTestID, SKillID, Name) values (8, '27', 'interdum');
insert into skill_test (SkillTestID, SKillID, Name) values (9, '33', 'nibh in');
insert into skill_test (SkillTestID, SKillID, Name) values (10, '9', 'lacinia nisi venenatis tristique');
insert into skill_test (SkillTestID, SKillID, Name) values (11, '46', 'luctus et');
insert into skill_test (SkillTestID, SKillID, Name) values (12, '40', 'sit');
insert into skill_test (SkillTestID, SKillID, Name) values (13, '38', 'justo pellentesque viverra pede ac');
insert into skill_test (SkillTestID, SKillID, Name) values (14, '37', 'sapien cursus vestibulum proin eu');
insert into skill_test (SkillTestID, SKillID, Name) values (15, '14', 'scelerisque');
insert into skill_test (SkillTestID, SKillID, Name) values (16, '3', 'ante ipsum primis in');
insert into skill_test (SkillTestID, SKillID, Name) values (17, '17', 'congue risus semper porta volutpat');
insert into skill_test (SkillTestID, SKillID, Name) values (18, '42', 'rutrum rutrum neque');
insert into skill_test (SkillTestID, SKillID, Name) values (19, '19', 'eros suspendisse accumsan tortor');
insert into skill_test (SkillTestID, SKillID, Name) values (20, '36', 'enim lorem ipsum dolor sit');
insert into skill_test (SkillTestID, SKillID, Name) values (21, '11', 'in purus eu magna vulputate');
insert into skill_test (SkillTestID, SKillID, Name) values (22, '12', 'lacinia');
insert into skill_test (SkillTestID, SKillID, Name) values (23, '23', 'sagittis');
insert into skill_test (SkillTestID, SKillID, Name) values (24, '32', 'ut');
insert into skill_test (SkillTestID, SKillID, Name) values (25, '5', 'diam erat fermentum justo nec');
insert into skill_test (SkillTestID, SKillID, Name) values (26, '7', 'semper interdum mauris ullamcorper purus');
insert into skill_test (SkillTestID, SKillID, Name) values (27, '48', 'in sagittis dui');
insert into skill_test (SkillTestID, SKillID, Name) values (28, '29', 'eget');
insert into skill_test (SkillTestID, SKillID, Name) values (29, '4', 'convallis morbi odio odio');
insert into skill_test (SkillTestID, SKillID, Name) values (30, '20', 'accumsan felis ut at dolor');
insert into skill_test (SkillTestID, SKillID, Name) values (31, '39', 'in hac habitasse platea');
insert into skill_test (SkillTestID, SKillID, Name) values (32, '18', 'sed');
insert into skill_test (SkillTestID, SKillID, Name) values (33, '25', 'odio odio elementum eu interdum');
insert into skill_test (SkillTestID, SKillID, Name) values (34, '21', 'dignissim');
insert into skill_test (SkillTestID, SKillID, Name) values (35, '34', 'sit amet eleifend pede libero');
insert into skill_test (SkillTestID, SKillID, Name) values (36, '22', 'placerat');
insert into skill_test (SkillTestID, SKillID, Name) values (37, '15', 'lacinia');
insert into skill_test (SkillTestID, SKillID, Name) values (38, '50', 'sit');
insert into skill_test (SkillTestID, SKillID, Name) values (39, '44', 'nulla');
insert into skill_test (SkillTestID, SKillID, Name) values (40, '2', 'sem');
insert into skill_test (SkillTestID, SKillID, Name) values (41, '49', 'sapien varius');
insert into skill_test (SkillTestID, SKillID, Name) values (42, '1', 'ut');
insert into skill_test (SkillTestID, SKillID, Name) values (43, '6', 'proin');
insert into skill_test (SkillTestID, SKillID, Name) values (44, '43', 'posuere metus');
insert into skill_test (SkillTestID, SKillID, Name) values (45, '45', 'in tempus sit amet sem');
insert into skill_test (SkillTestID, SKillID, Name) values (46, '10', 'primis');
insert into skill_test (SkillTestID, SKillID, Name) values (47, '41', 'massa tempor');
insert into skill_test (SkillTestID, SKillID, Name) values (48, '8', 'ut');
insert into skill_test (SkillTestID, SKillID, Name) values (49, '16', 'est risus');
insert into skill_test (SkillTestID, SKillID, Name) values (50, '26', 'sit amet');
